//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loango_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livres
    {
        public int id_livre { get; set; }
        public string titre_livre { get; set; }
        public System.DateTime date_acqui_livre { get; set; }
        public Nullable<System.DateTime> anné_pub_livre { get; set; }
        public int nbre_page_livre { get; set; }
        public int id_auteur_liv { get; set; }
        public Nullable<int> id_cat_liv { get; set; }
        public Nullable<int> id_rayon_liv { get; set; }
        public Nullable<int> id_edition_liv { get; set; }
        public Nullable<int> id_user_liv { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Edition Edition { get; set; }
        public virtual Rayon Rayon { get; set; }
        public virtual User User { get; set; }
    }
}
