//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loango_app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Loango_dbEntities1 : DbContext
    {
        public Loango_dbEntities1()
            : base("name=Loango_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteur> Auteur { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Edition> Edition { get; set; }
        public virtual DbSet<Livres> Livres { get; set; }
        public virtual DbSet<Rayon> Rayon { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
